//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVEMon.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NetworkConstants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NetworkConstants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EVEMon.Common.NetworkConstants", typeof(NetworkConstants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.eveonline.com/api/default.asp.
        /// </summary>
        public static string APIAccountCredentials {
            get {
                return ResourceManager.GetString("APIAccountCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /account/AccountStatus.xml.aspx.
        /// </summary>
        public static string APIAccountStatus {
            get {
                return ResourceManager.GetString("APIAccountStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://apiserve.evemu.com:64.
        /// </summary>
        public static string APIBase {
            get {
                return ResourceManager.GetString("APIBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/AccountBalance.xml.aspx.
        /// </summary>
        public static string APICharacterAccountBalance {
            get {
                return ResourceManager.GetString("APICharacterAccountBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /account/Characters.xml.aspx.
        /// </summary>
        public static string APICharacterList {
            get {
                return ResourceManager.GetString("APICharacterList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /eve/CharacterName.xml.aspx.
        /// </summary>
        public static string APICharacterName {
            get {
                return ResourceManager.GetString("APICharacterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/CharacterSheet.xml.aspx.
        /// </summary>
        public static string APICharacterSheet {
            get {
                return ResourceManager.GetString("APICharacterSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/SkillInTraining.xml.aspx.
        /// </summary>
        public static string APICharacterSkillInTraining {
            get {
                return ResourceManager.GetString("APICharacterSkillInTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /eve/ConquerableStationList.xml.aspx.
        /// </summary>
        public static string APIConquerableStationList {
            get {
                return ResourceManager.GetString("APIConquerableStationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /corp/IndustryJobs.xml.aspx.
        /// </summary>
        public static string APICorporationIndustryJobs {
            get {
                return ResourceManager.GetString("APICorporationIndustryJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /corp/MarketOrders.xml.aspx.
        /// </summary>
        public static string APICorporationMarketOrders {
            get {
                return ResourceManager.GetString("APICorporationMarketOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/IndustryJobs.xml.aspx.
        /// </summary>
        public static string APIIndustryJobs {
            get {
                return ResourceManager.GetString("APIIndustryJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/MailBodies.xml.aspx.
        /// </summary>
        public static string APIMailBodies {
            get {
                return ResourceManager.GetString("APIMailBodies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/MailingLists.xml.aspx.
        /// </summary>
        public static string APIMailingLists {
            get {
                return ResourceManager.GetString("APIMailingLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/MailMessages.xml.aspx.
        /// </summary>
        public static string APIMailMessages {
            get {
                return ResourceManager.GetString("APIMailMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/MarketOrders.xml.aspx.
        /// </summary>
        public static string APIMarketOrders {
            get {
                return ResourceManager.GetString("APIMarketOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/Notifications.xml.aspx.
        /// </summary>
        public static string APINotifications {
            get {
                return ResourceManager.GetString("APINotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/NotificationTexts.xml.aspx.
        /// </summary>
        public static string APINotificationTexts {
            get {
                return ResourceManager.GetString("APINotificationTexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/Research.xml.aspx.
        /// </summary>
        public static string APIResearchPoints {
            get {
                return ResourceManager.GetString("APIResearchPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /server/ServerStatus.xml.aspx.
        /// </summary>
        public static string APIServerStatus {
            get {
                return ResourceManager.GetString("APIServerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/SkillQueue.xml.aspx.
        /// </summary>
        public static string APISkillQueue {
            get {
                return ResourceManager.GetString("APISkillQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://apitest.eveonline.com.
        /// </summary>
        public static string APITestBase {
            get {
                return ResourceManager.GetString("APITestBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.battleclinic.com/time.php.
        /// </summary>
        public static string BatlleclinicTimeSynch {
            get {
                return ResourceManager.GetString("BatlleclinicTimeSynch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.battleclinic.com.
        /// </summary>
        public static string BattleClinicBase {
            get {
                return ResourceManager.GetString("BattleClinicBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://eve.battleclinic.com/ship_loadout_feed.php?id={0}.
        /// </summary>
        public static string BattleclinicLoadoutDetails {
            get {
                return ResourceManager.GetString("BattleclinicLoadoutDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://eve.battleclinic.com/ship_loadout_feed.php?typeID={0}.
        /// </summary>
        public static string BattleclinicLoadoutsFeed {
            get {
                return ResourceManager.GetString("BattleclinicLoadoutsFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://forum.battleclinic.com/index.php/topic,{0}.0.html.
        /// </summary>
        public static string BattleclinicLoadoutTopic {
            get {
                return ResourceManager.GetString("BattleclinicLoadoutTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://evemon.static.battleclinic.com/builds/patch.xml.
        /// </summary>
        public static string BattleclinicUpdates {
            get {
                return ResourceManager.GetString("BattleclinicUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.battleclinic.com/api_key.php.
        /// </summary>
        public static string BCAPIAccountCredentials {
            get {
                return ResourceManager.GetString("BCAPIAccountCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.battleclinic.com.
        /// </summary>
        public static string BCAPIBase {
            get {
                return ResourceManager.GetString("BCAPIBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /account/checkAPICredentials.php.
        /// </summary>
        public static string BCAPICheckCredentials {
            get {
                return ResourceManager.GetString("BCAPICheckCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /files/fileGet.php.
        /// </summary>
        public static string BCAPIFileGet {
            get {
                return ResourceManager.GetString("BCAPIFileGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /files/fileGetByName.php.
        /// </summary>
        public static string BCAPIFileGetByName {
            get {
                return ResourceManager.GetString("BCAPIFileGetByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /files/fileSave.php.
        /// </summary>
        public static string BCAPIFileSave {
            get {
                return ResourceManager.GetString("BCAPIFileSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://eve.no-ip.de/{0}/{1}/{2}.png.
        /// </summary>
        public static string CCPIcons {
            get {
                return ResourceManager.GetString("CCPIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://image.eveonline.com/{0}/{1}_{2}.png.
        /// </summary>
        public static string CCPIconsFromImageServer {
            get {
                return ResourceManager.GetString("CCPIconsFromImageServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://image.eveonline.com/character/{0}_128.jpg.
        /// </summary>
        public static string CCPPortraits {
            get {
                return ResourceManager.GetString("CCPPortraits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://wiki.battleclinic.com/index.php/How_to_write_an_useful_bug_report_%28EVEMon%29_%3F.
        /// </summary>
        public static string EVEMonBugReport {
            get {
                return ResourceManager.GetString("EVEMonBugReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://forum.battleclinic.com/index.php#c36.
        /// </summary>
        public static string EVEMonForums {
            get {
                return ResourceManager.GetString("EVEMonForums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://wiki.battleclinic.com/index.php/Known_problems_%28EVEMon%29.
        /// </summary>
        public static string EVEMonKnownProblems {
            get {
                return ResourceManager.GetString("EVEMonKnownProblems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://evemon.battleclinic.com/.
        /// </summary>
        public static string EVEMonMainPage {
            get {
                return ResourceManager.GetString("EVEMonMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://evemon.uservoice.com/.
        /// </summary>
        public static string EVEMonUserVoice {
            get {
                return ResourceManager.GetString("EVEMonUserVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.google.com/calendar/feeds/default/private/full.
        /// </summary>
        public static string GoogleCalendarURL {
            get {
                return ResourceManager.GetString("GoogleCalendarURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.eveonline.com/bitmaps/character/level.
        /// </summary>
        public static string MyEVELevelImage {
            get {
                return ResourceManager.GetString("MyEVELevelImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://area51.stackexchange.com/proposals/3371/eve-online?referrer=YrSyuyuqKBzSZ2Kzwn8oXQ2.
        /// </summary>
        public static string StackExchangeEveOnlineURL {
            get {
                return ResourceManager.GetString("StackExchangeEveOnlineURL", resourceCulture);
            }
        }
    }
}
