/*
 * Configuration header, generated by 'cmake' during compilation.
 */

/*
 * Platform defines
 */
// X64
// Define this if you are under an X64-based operating system.
#cmakedefine X64 1

// BIG_ENDIAN
// Define this if you are on a big-endian system.
#cmakedefine BIG_ENDIAN 1

// WIN32
// Define this if you are on Windows.
// CMake passes this as a command-line define.

// CYGWIN
// Define this if you are under CYGWIN.
#cmakedefine CYGWIN 1

// FREE_BSD
// Define this if you are on FreeBSD.
#cmakedefine FREE_BSD 1

// APPLE
// Define this if you are on Apple's OS.
#cmakedefine APPLE 1

/*
 * Compiler defines
 */
// MSVC
// Define this if you are using Microsoft C++ Compiler.
#cmakedefine MSVC 1

// GNUC
// Define this if you are using GNU C++ compiler.
#cmakedefine GNUC 1

/*
 * Configuration
 */
// NDEBUG
// Define this if you want a non-debug (release) build
// CMake passes this as a command-line define.

// TINYXML_USE_STL
// Define this if tinyxml should use native STL.
#cmakedefine TINYXML_USE_STL 1

// EVEMU_REVISION
// The revision of the source working tree.
#define EVEMU_REVISION "@EVEMU_REVISION@"

