//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVEMon.Common.Net {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EVEMon.Common.Net.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A request to {0} failed because EVEMon was unable to connect to the server. Please check your network and/or firewall settings..
        /// </summary>
        internal static string ConnectFailure {
            get {
                return ResourceManager.GetString("ConnectFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file request to {0} failed because the file could not be written..
        /// </summary>
        internal static string FileException {
            get {
                return ResourceManager.GetString("FileException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Image request  to {0} failed because the server did not return a valid image..
        /// </summary>
        internal static string ImageException {
            get {
                return ResourceManager.GetString("ImageException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A request to {0} failed because the name resolver service could not resolve the host name. Please check your network settings..
        /// </summary>
        internal static string NameResolutionFailure {
            get {
                return ResourceManager.GetString("NameResolutionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The proxy server at {0} rejected a request to {1}. Please verify that you have specified the correct user name and password..
        /// </summary>
        internal static string ProxyAuthenticationFailure {
            get {
                return ResourceManager.GetString("ProxyAuthenticationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The proxy server at {0} rejected a request to {1}. Please verify that you have specified the correct user name and password. Web requests have been temporarily disabled until your proxy settings have been updated..
        /// </summary>
        internal static string ProxyAuthenticationFailureDisabledRequests {
            get {
                return ResourceManager.GetString("ProxyAuthenticationFailureDisabledRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name resolver service could not resolve the proxy host name &quot;{0}&quot;. Please verify that you have specified the correct proxy server, or check your network settings..
        /// </summary>
        internal static string ProxyNameResolutionFailure {
            get {
                return ResourceManager.GetString("ProxyNameResolutionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of redirects was exceeded while attempting to retrieve data from {0}..
        /// </summary>
        internal static string RedirectsExceeded {
            get {
                return ResourceManager.GetString("RedirectsExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A request to {0} was not permitted by the proxy at {1}..
        /// </summary>
        internal static string RequestProhibitedByProxy {
            get {
                return ResourceManager.GetString("RequestProhibitedByProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A request to {0} failed because web requests have been temporarily disabled..
        /// </summary>
        internal static string RequestsDisabled {
            get {
                return ResourceManager.GetString("RequestsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The web server at {0} returned an error. The full response returned by the web server was:.
        /// </summary>
        internal static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A request to {0} failed because no response was received during the timeout period..
        /// </summary>
        internal static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A request to {0} failed with status {1}..
        /// </summary>
        internal static string UnknownWebException {
            get {
                return ResourceManager.GetString("UnknownWebException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Xml request to {0} failed because the server did not return a valid Xml document.
        /// </summary>
        internal static string XmlException {
            get {
                return ResourceManager.GetString("XmlException", resourceCulture);
            }
        }
    }
}
