
CXXFLAGS=-ggdb -O -pipe -Wall -I../common -I/usr/local/mysql/include \
  -I. -fno-inline -DFREEBSD
LDFLAGS=-lpcap -lz -O2 -ggdb -pipe -ldl -lpthread \
  -L/usr/local/mysql/lib -lmysqlclient -lreadline

everything: all

include .depend

include Makefile.common


