//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVEMon.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EVEMon.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap AccountManagement {
            get {
                object obj = ResourceManager.GetObject("AccountManagement", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap AddAccount {
            get {
                object obj = ResourceManager.GetObject("AddAccount", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap APIKeyFull {
            get {
                object obj = ResourceManager.GetObject("APIKeyFull", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap APIKeyFull16 {
            get {
                object obj = ResourceManager.GetObject("APIKeyFull16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap APIKeyLimited {
            get {
                object obj = ResourceManager.GetObject("APIKeyLimited", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap APIKeyLimited16 {
            get {
                object obj = ResourceManager.GetObject("APIKeyLimited16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap APIKeyWrong {
            get {
                object obj = ResourceManager.GetObject("APIKeyWrong", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap AttributeOptimize {
            get {
                object obj = ResourceManager.GetObject("AttributeOptimize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BlueGlassArrow {
            get {
                object obj = ResourceManager.GetObject("BlueGlassArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Blueprint {
            get {
                object obj = ResourceManager.GetObject("Blueprint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Bug {
            get {
                object obj = ResourceManager.GetObject("Bug", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Calendar {
            get {
                object obj = ResourceManager.GetObject("Calendar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Certificate_24 {
            get {
                object obj = ResourceManager.GetObject("Certificate_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Certificate_32 {
            get {
                object obj = ResourceManager.GetObject("Certificate_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Certificate_64 {
            get {
                object obj = ResourceManager.GetObject("Certificate_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Clock {
            get {
                object obj = ResourceManager.GetObject("Clock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Collapse {
            get {
                object obj = ResourceManager.GetObject("Collapse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Comment {
            get {
                object obj = ResourceManager.GetObject("Comment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Copy {
            get {
                object obj = ResourceManager.GetObject("Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap CrossBlack {
            get {
                object obj = ResourceManager.GetObject("CrossBlack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap CrossGray {
            get {
                object obj = ResourceManager.GetObject("CrossGray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Deadspace {
            get {
                object obj = ResourceManager.GetObject("Deadspace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap DeleteAccount {
            get {
                object obj = ResourceManager.GetObject("DeleteAccount", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap DeleteCharacter {
            get {
                object obj = ResourceManager.GetObject("DeleteCharacter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap DeletePlan {
            get {
                object obj = ResourceManager.GetObject("DeletePlan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap EditAccount {
            get {
                object obj = ResourceManager.GetObject("EditAccount", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap EditChar {
            get {
                object obj = ResourceManager.GetObject("EditChar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap EditPlan {
            get {
                object obj = ResourceManager.GetObject("EditPlan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Error16 {
            get {
                object obj = ResourceManager.GetObject("Error16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Error32 {
            get {
                object obj = ResourceManager.GetObject("Error32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap EVEMail {
            get {
                object obj = ResourceManager.GetObject("EVEMail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap EVEMon16 {
            get {
                object obj = ResourceManager.GetObject("EVEMon16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Exit {
            get {
                object obj = ResourceManager.GetObject("Exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Expand {
            get {
                object obj = ResourceManager.GetObject("Expand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ExportArrow {
            get {
                object obj = ResourceManager.GetObject("ExportArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ExportCharacter {
            get {
                object obj = ResourceManager.GetObject("ExportCharacter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ExportPlan {
            get {
                object obj = ResourceManager.GetObject("ExportPlan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Faction {
            get {
                object obj = ResourceManager.GetObject("Faction", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Folder {
            get {
                object obj = ResourceManager.GetObject("Folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Forum {
            get {
                object obj = ResourceManager.GetObject("Forum", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Grouping {
            get {
                object obj = ResourceManager.GetObject("Grouping", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Help {
            get {
                object obj = ResourceManager.GetObject("Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap HideCharacter {
            get {
                object obj = ResourceManager.GetObject("HideCharacter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ImplantCalculator {
            get {
                object obj = ResourceManager.GetObject("ImplantCalculator", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ImportCharacter {
            get {
                object obj = ResourceManager.GetObject("ImportCharacter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Industry {
            get {
                object obj = ResourceManager.GetObject("Industry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Information16 {
            get {
                object obj = ResourceManager.GetObject("Information16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap JumpClone {
            get {
                object obj = ResourceManager.GetObject("JumpClone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap LeadsTo {
            get {
                object obj = ResourceManager.GetObject("LeadsTo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap List {
            get {
                object obj = ResourceManager.GetObject("List", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap LoadPlan {
            get {
                object obj = ResourceManager.GetObject("LoadPlan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap LoadSettings {
            get {
                object obj = ResourceManager.GetObject("LoadSettings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Magnifier {
            get {
                object obj = ResourceManager.GetObject("Magnifier", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap messagebox {
            get {
                object obj = ResourceManager.GetObject("messagebox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Mineral {
            get {
                object obj = ResourceManager.GetObject("Mineral", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Money {
            get {
                object obj = ResourceManager.GetObject("Money", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap MoveDown {
            get {
                object obj = ResourceManager.GetObject("MoveDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap MoveUp {
            get {
                object obj = ResourceManager.GetObject("MoveUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap NewPlan {
            get {
                object obj = ResourceManager.GetObject("NewPlan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Notification {
            get {
                object obj = ResourceManager.GetObject("Notification", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;NotificationRefTypeIDs xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///	&lt;rowset name=&quot;refTypes&quot; key=&quot;refTypeID&quot; columns=&quot;refTypeID,refTypeName&quot;&gt;
        ///		&lt;row refTypeID=&quot;2&quot; refTypeName=&quot;Character deleted&quot; /&gt;
        ///		&lt;row refTypeID=&quot;3&quot; refTypeName=&quot;Give medal to character&quot; /&gt;
        ///		&lt;row refTypeID=&quot;4&quot; refTypeName=&quot;Alliance maintenance bill&quot; /&gt;
        ///		&lt;row refTypeID=&quot;5&quot; refTypeName=&quot;Alliance war declared&quot; /&gt;
        ///		&lt;row refTypeID=&quot;6&quot; refTypeName=&quot;Alliance  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NotificationRefTypeIDs {
            get {
                return ResourceManager.GetString("NotificationRefTypeIDs", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap Officer {
            get {
                object obj = ResourceManager.GetObject("Officer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Omega {
            get {
                object obj = ResourceManager.GetObject("Omega", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Online {
            get {
                object obj = ResourceManager.GetObject("Online", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap OwnedBook {
            get {
                object obj = ResourceManager.GetObject("OwnedBook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap PieChart {
            get {
                object obj = ResourceManager.GetObject("PieChart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Plan {
            get {
                object obj = ResourceManager.GetObject("Plan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap PlanCharacter {
            get {
                object obj = ResourceManager.GetObject("PlanCharacter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Printer {
            get {
                object obj = ResourceManager.GetObject("Printer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Problem {
            get {
                object obj = ResourceManager.GetObject("Problem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Rename {
            get {
                object obj = ResourceManager.GetObject("Rename", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Research {
            get {
                object obj = ResourceManager.GetObject("Research", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Reset {
            get {
                object obj = ResourceManager.GetObject("Reset", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;
        ///    xmlns:msxsl=&quot;urn:schemas-microsoft-com:xslt&quot; exclude-result-prefixes=&quot;msxsl&quot;
        ///&gt;
        ///  &lt;xsl:strip-space elements=&quot;*&quot;/&gt;
        ///  &lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot;/&gt;
        ///
        ///  &lt;xsl:template match=&quot;@* | node()&quot;&gt;
        ///    &lt;xsl:copy&gt;
        ///      &lt;xsl:apply-templates select=&quot;@* | node()&quot;/&gt;
        ///    &lt;/xsl:copy&gt;
        ///  &lt;/xsl:template&gt;
        ///
        ///  &lt;!-- Rowsets are transformed into something else--&gt;
        ///  &lt;xsl:template match=&quot;rowset [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RowsetsXSLT {
            get {
                return ResourceManager.GetString("RowsetsXSLT", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap SaveSettings {
            get {
                object obj = ResourceManager.GetObject("SaveSettings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SchedulerAdd {
            get {
                object obj = ResourceManager.GetObject("SchedulerAdd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SchedulerClear {
            get {
                object obj = ResourceManager.GetObject("SchedulerClear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SchedulerDelete {
            get {
                object obj = ResourceManager.GetObject("SchedulerDelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Settings {
            get {
                object obj = ResourceManager.GetObject("Settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;
        ///    xmlns:msxsl=&quot;urn:schemas-microsoft-com:xslt&quot; exclude-result-prefixes=&quot;msxsl&quot;
        ///&gt;
        ///    &lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot;/&gt;
        ///
        ///  &lt;!-- Root --&gt;
        ///  &lt;xsl:template match=&quot;logindata2&quot;&gt;
        ///    &lt;xsl:element name=&quot;OldSettings&quot;&gt;
        ///      &lt;xsl:element name=&quot;accounts&quot;&gt;
        ///        &lt;xsl:for-each select=&quot;Accounts/AccountDetails&quot;&gt;
        ///          &lt;xsl:call-template name=&quot;account&quot;/&gt;
        ///        &lt;/xsl:for-each&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SettingsAndPlanImport {
            get {
                return ResourceManager.GetString("SettingsAndPlanImport", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap Ship {
            get {
                object obj = ResourceManager.GetObject("Ship", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Skill16 {
            get {
                object obj = ResourceManager.GetObject("Skill16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Skill32 {
            get {
                object obj = ResourceManager.GetObject("Skill32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Skills {
            get {
                object obj = ResourceManager.GetObject("Skills", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SkillsQueue {
            get {
                object obj = ResourceManager.GetObject("SkillsQueue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.IO.UnmanagedMemoryStream SkillTrained {
            get {
                return ResourceManager.GetStream("SkillTrained", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap Storyline {
            get {
                object obj = ResourceManager.GetObject("Storyline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap T1 {
            get {
                object obj = ResourceManager.GetObject("T1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap T2 {
            get {
                object obj = ResourceManager.GetObject("T2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap T3 {
            get {
                object obj = ResourceManager.GetObject("T3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap T4 {
            get {
                object obj = ResourceManager.GetObject("T4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Throbber {
            get {
                object obj = ResourceManager.GetObject("Throbber", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Toggle {
            get {
                object obj = ResourceManager.GetObject("Toggle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Transparent {
            get {
                object obj = ResourceManager.GetObject("Transparent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap TrayIcon {
            get {
                object obj = ResourceManager.GetObject("TrayIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Warning16 {
            get {
                object obj = ResourceManager.GetObject("Warning16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Warning32 {
            get {
                object obj = ResourceManager.GetObject("Warning32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Window {
            get {
                object obj = ResourceManager.GetObject("Window", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
        ///  &lt;xsl:template match=&quot;outputCharacter&quot;&gt;
        ///    &lt;html&gt;
        ///      &lt;head&gt;
        ///        &lt;title&gt;
        ///          Character Sheet :: &lt;xsl:value-of select=&quot;@name&quot;/&gt;
        ///        &lt;/title&gt;
        ///      &lt;/head&gt;
        ///      &lt;body&gt;
        ///        &lt;table&gt;
        ///          &lt;tr&gt;
        ///            &lt;td&gt;
        ///              &lt;xsl:element name=&quot;img&quot;&gt;
        ///                &lt;xsl:attribute name=&quot;src&quot;&gt;
        ///                  http://img.eve.is/serv.asp?s=256&amp;amp;c=&lt;xsl: [rest of string was truncated]&quot;;.
        /// </summary>
        public static string XmlToHtmlXslt {
            get {
                return ResourceManager.GetString("XmlToHtmlXslt", resourceCulture);
            }
        }
    }
}
