# Generated by CacheToSQL 2 on 12/12/2011 7:56:29 AM (UTC)
# Source: cacheChrDefaultOverviews
# File: 3200011.cache2

DROP TABLE IF EXISTS overviewDefaults;
DROP TABLE IF EXISTS chrDefaultOverviews;
CREATE TABLE chrDefaultOverviews (
    overviewID INT,
    overviewName TEXT,
    overviewShortName TEXT,
    overviewNameID INT,
    dataID INT,
    PRIMARY KEY (overviewID),
    INDEX overviewNameID (overviewNameID),
    INDEX dataID (dataID)
);

INSERT INTO chrDefaultOverviews (overviewID, overviewName, overviewShortName, overviewNameID, dataID) VALUES (3, 'PvP', 'defaultpvp', 59570, 16533082);
INSERT INTO chrDefaultOverviews (overviewID, overviewName, overviewShortName, overviewNameID, dataID) VALUES (4, 'Mining', 'defaultmining', 59571, 16533083);
INSERT INTO chrDefaultOverviews (overviewID, overviewName, overviewShortName, overviewNameID, dataID) VALUES (5, 'WarpTo', 'defaultwarpto', 59572, 16533084);
INSERT INTO chrDefaultOverviews (overviewID, overviewName, overviewShortName, overviewNameID, dataID) VALUES (6, 'Loot', 'defaultloot', 59573, 16533085);
INSERT INTO chrDefaultOverviews (overviewID, overviewName, overviewShortName, overviewNameID, dataID) VALUES (8, 'All', 'defaultall', 59574, 16533086);
INSERT INTO chrDefaultOverviews (overviewID, overviewName, overviewShortName, overviewNameID, dataID) VALUES (12, 'Drones', 'defaultdrones', 59575, 16533087);
INSERT INTO chrDefaultOverviews (overviewID, overviewName, overviewShortName, overviewNameID, dataID) VALUES (13, 'General', 'default', 59576, 16533088);

