# Generated by CacheToSQL on 19.04.2011 23:28:04 (UTC)
# Source: config.BulkData.schematics
# File: 32f9

DROP TABLE IF EXISTS schematics;
CREATE TABLE schematics (
    schematicID INT,
    schematicName TEXT,
    cycleTime INT,
    dataID INT,
    PRIMARY KEY (schematicID),
    INDEX dataID (dataID)
);

INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (65, 'Super Conductors', 3600, 8810795);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (66, 'Coolant', 3600, 8810753);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (67, 'Rocket Fuel', 3600, 8810791);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (68, 'Synthetic Oil', 3600, 8810798);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (69, 'Oxides', 3600, 8810779);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (70, 'Silicate Glass', 3600, 8810792);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (71, 'Transmitter', 3600, 8810803);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (72, 'Water-Cooled CPU', 3600, 8810808);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (73, 'Mechanical Parts', 3600, 8810769);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (74, 'Construction Blocks', 3600, 8810751);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (75, 'Enriched Uranium', 3600, 8810758);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (76, 'Consumer Electronics', 3600, 8810752);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (77, 'Miniature Electronics', 3600, 8810772);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (78, 'Nanites', 3600, 8810773);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (79, 'Biocells', 3600, 8810742);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (80, 'Microfiber Shielding', 3600, 8810771);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (81, 'Viral Agent', 3600, 8810806);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (82, 'Fertilizer', 3600, 8810759);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (83, 'Genetically Enhanced Livestock', 3600, 8810761);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (84, 'Livestock', 3600, 8810768);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (85, 'Polytextiles', 3600, 8810785);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (86, 'Test Cultures', 3600, 8810800);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (87, 'Supertensile Plastics', 3600, 8810797);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (88, 'Polyaramids', 3600, 8810784);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (89, 'Ukomi Super Conductor', 3600, 8810804);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (90, 'Condensates', 3600, 8810750);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (91, 'Camera Drones', 3600, 8810747);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (92, 'Synthetic Synapses', 3600, 8810799);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (94, 'High-Tech Transmitter', 3600, 8810765);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (95, 'Gel-Matrix Biopaste', 3600, 8810760);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (96, 'Supercomputers', 3600, 8810796);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (97, 'Robotics', 3600, 8810790);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (98, 'Smartfab Units', 3600, 8810794);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (99, 'Nuclear Reactors', 3600, 8810778);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (100, 'Guidance Systems', 3600, 8810762);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (102, 'Neocoms', 3600, 8810775);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (103, 'Planetary Vehicles', 3600, 8810782);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (104, 'Biotech Research Reports', 3600, 8810746);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (105, 'Vaccines', 3600, 8810805);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (106, 'Industrial Explosives', 3600, 8810766);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (107, 'Hermetic Membranes', 3600, 8810764);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (108, 'Transcranial Microcontroller', 3600, 8810802);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (109, 'Data Chips', 3600, 8810756);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (110, 'Hazmat Detection Systems', 3600, 8810763);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (111, 'Cryoprotectant Solution', 3600, 8810754);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (112, 'Organic Mortar Applicators', 3600, 8838284);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (113, 'Sterile Conduits', 3600, 8838287);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (114, 'Nano-Factory', 3600, 8810774);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (115, 'Self-Harmonizing Power Core', 3600, 8838286);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (116, 'Recursive Computing Module', 3600, 8838285);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (117, 'Broadcast Node', 3600, 8838282);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (118, 'Integrity Response Drones', 3600, 8838283);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (119, 'Wetware Mainframe', 3600, 8810809);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (121, 'Water', 1800, 8810807);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (122, 'Plasmoids', 1800, 8810783);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (123, 'Electrolytes', 1800, 8810757);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (124, 'Oxygen', 1800, 8810781);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (125, 'Oxidizing Compound', 1800, 8810780);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (126, 'Reactive Metals', 1800, 8810789);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (127, 'Precious Metals', 1800, 8810786);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (128, 'Toxic Metals', 1800, 8810801);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (129, 'Chiral Structures', 1800, 8810749);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (130, 'Silicon', 1800, 8810793);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (131, 'Bacteria', 1800, 8810741);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (132, 'Biomass', 1800, 8810744);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (133, 'Proteins', 1800, 8810787);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (134, 'Biofuels', 1800, 8810743);
INSERT INTO schematics (schematicID, schematicName, cycleTime, dataID) VALUES (135, 'Industrial Fibers', 1800, 8810767);
