DROP TABLE IF EXISTS crtClasses;

CREATE TABLE crtClasses
(
  classID INT,
  className VARCHAR(150),
  description TEXT,
  classNameID INT,
  PRIMARY KEY (classID)
);

INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (2, 'Core Fitting', 'Core Fitting', 59287);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (3, 'Core Capacitor', 'Core Capacitor', 59288);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (4, 'Core Targeting', 'Core Targeting', 59289);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (5, 'Core Navigation', 'Core Navigation', 59290);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (6, 'Core Competency', 'Core Competency', 59291);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (7, 'Core Integrity', 'Core Integrity', 59292);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (8, 'Amarr Military - Soldier', 'Amarr Military - Soldier', 59372);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (9, 'Amarr Military - Special Forces', 'Amarr Military - Special Forces', 59374);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (10, 'Amarr Industry - Engineer', 'Amarr Industry - Engineer', 59375);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (11, 'Amarr Industry - Prospector', 'Amarr Industry - Prospector', 59376);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (12, 'Amarr Business - Entrepreneur', 'Amarr Business - Entrepreneur', 59377);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (13, 'Amarr Business - Executive Commander', 'Amarr Business - Executive Commander', 59378);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (14, 'Caldari Military - Soldier', 'Caldari Military - Soldier', 59379);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (15, 'Caldari Military - Special Forces', 'Caldari Military - Special Forces', 59380);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (16, 'Caldari Industry - Engineer', 'Caldari Industry - Engineer', 59381);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (17, 'Caldari Industry - Prospector', 'Caldari Industry - Prospector', 59382);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (18, 'Caldari Business - Entrepreneur', 'Caldari Business - Entrepreneur', 59383);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (19, 'Caldari Business - Executive Commander', 'Caldari Business - Executive Commander', 59384);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (20, 'Gallente Military - Soldier', 'Gallente Military - Soldier', 59385);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (21, 'Gallente Military - Special Forces', 'Gallente Military - Special Forces', 59386);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (22, 'Gallente Industry - Engineer', 'Gallente Industry - Engineer', 59387);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (23, 'Gallente Industry - Prospector', 'Gallente Industry - Prospector', 59388);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (24, 'Gallente Business - Entrepreneur', 'Gallente Business - Entrepreneur', 59389);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (25, 'Gallente Business - Executive Commander', 'Gallente Business - Executive Commander', 59390);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (26, 'Minmatar Military - Soldier', 'Minmatar Military - Soldier', 59391);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (27, 'Minmatar Military - Special Forces', 'Minmatar Military - Special Forces', 59392);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (28, 'Minmatar Industry - Engineer', 'Minmatar Industry - Engineer', 59393);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (29, 'Minmatar Industry - Prospector', 'Minmatar Industry - Prospector', 59394);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (30, 'Minmatar Business - Entrepreneur', 'Minmatar Business - Entrepreneur', 59395);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (31, 'Minmatar Business - Executive Commander', 'Minmatar Business - Executive Commander', 59373);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (32, 'Armor Tanking', 'Armor Tanking', 59293);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (33, 'Armor Reinforcement', 'Armor Reinforcement', 59294);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (34, 'Active Shield Tanking', 'Active Shield Tanking', 59295);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (35, 'Passive Shield Tanking', 'Passive Shield Tanking', 59296);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (36, 'Shield Reinforcement', 'Shield Reinforcement', 59297);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (37, 'Hull Tanking', 'Hull Tanking', 59298);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (38, 'Logistics Chief', 'Logistics Chief', 59299);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (39, 'Turret Control', 'Turret Control', 59300);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (40, 'Frigate Energy Turrets', 'Frigate Energy Turrets', 59301);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (41, 'Frigate Advanced Pulse Turrets', 'Frigate Advanced Pulse Turrets', 59302);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (42, 'Frigate Advanced Beam Turrets', 'Frigate Advanced Beam Turrets', 59303);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (43, 'Cruiser Energy Turrets', 'Cruiser Energy Turrets', 59304);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (44, 'Cruiser Advanced Pulse Turrets', 'Cruiser Advanced Pulse Turrets', 59305);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (45, 'Cruiser Advanced Beam Turrets', 'Cruiser Advanced Beam Turrets', 59306);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (46, 'Battleship Energy Turrets', 'Battleship Energy Turrets', 59307);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (47, 'Battleship Advanced Pulse Turrets', 'Battleship Advanced Pulse Turrets', 59308);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (48, 'Battleship Advanced Beam Turrets', 'Battleship Advanced Beam Turrets', 59309);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (49, 'Frigate Hybrid Turrets', 'Frigate Hybrid Turrets', 59310);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (50, 'Frigate Advanced Blaster Turrets', 'Frigate Advanced Blaster Turrets', 59311);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (51, 'Frigate Advanced Rail Turrets', 'Frigate Advanced Rail Turrets', 59312);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (52, 'Cruiser Hybrid Turrets', 'Cruiser Hybrid Turrets', 59400);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (53, 'Cruiser Advanced Blaster Turrets', 'Cruiser Advanced Blaster Turrets', 59313);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (54, 'Cruiser Advanced Rail Turrets', 'Cruiser Advanced Rail Turrets', 59314);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (55, 'Battleship Hybrid Turrets', 'Battleship Hybrid Turrets', 59315);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (56, 'Battleship Advanced Blaster Turrets', 'Battleship Advanced Blaster Turrets', 59316);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (57, 'Battleship Advanced Rail Turrets', 'Battleship Advanced Rail Turrets', 59317);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (58, 'Frigate Projectile Turrets', 'Frigate Projectile Turrets', 59318);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (59, 'Frigate Advanced Autocannon Turrets', 'Frigate Advanced Autocannon Turrets', 59319);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (60, 'Frigate Advanced Artillery Turrets', 'Frigate Advanced Artillery Turrets', 59320);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (61, 'Cruiser Projectile Turrets', 'Cruiser Projectile Turrets', 59321);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (62, 'Cruiser Advanced Autocannon Turrets', 'Cruiser Advanced Autocannon Turrets', 59322);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (63, 'Cruiser Advanced Artillery Turrets', 'Cruiser Advanced Artillery Turrets', 59323);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (64, 'Battleship Projectile Turrets', 'Battleship Projectile Turrets', 59324);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (65, 'Battleship Advanced Autocannon Turrets', 'Battleship Advanced Autocannon Turrets', 59325);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (66, 'Battleship Advanced Artillery Turrets', 'Battleship Advanced Artillery Turrets', 59326);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (67, 'Missile Control', 'Missile Control', 59327);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (68, 'Frigate Launcher Control', 'Frigate Launcher Control', 59328);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (69, 'Frigate Advanced Standard Launchers', 'Frigate Advanced Standard Launchers', 59329);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (70, 'Frigate Advanced Rocket Launchers', 'Frigate Advanced Rocket Launchers', 59330);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (71, 'Cruiser Launcher Control', 'Cruiser Launcher Control', 59331);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (72, 'Cruiser Advanced Heavy Launchers', 'Cruiser Advanced Heavy Launchers', 59332);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (73, 'Cruiser Advanced Heavy Assault Launchers', 'Cruiser Advanced Heavy Assault Launchers', 59333);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (74, 'Battleship Launcher Control', 'Battleship Launcher Control', 59334);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (75, 'Battleship Advanced Cruise Launchers', 'Battleship Advanced Cruise Launchers', 59335);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (76, 'Battleship Advanced Siege Launchers', 'Battleship Advanced Siege Launchers', 59336);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (77, 'Drone Control', 'Drone Control', 59337);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (78, 'Combat Drone Control', 'Combat Drone Control', 59338);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (79, 'Heavy Drone Control', 'Heavy Drone Control', 59339);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (80, 'Specialist Drone Operator', 'Specialist Drone Operator', 59340);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (81, 'Elite Drone Operator', 'Elite Drone Operator', 59341);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (82, 'EWAR Operator', 'EWAR Operator', 59342);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (83, 'Cloak Operator', 'Cloak Operator', 59343);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (84, 'Target Painter Operator', 'Target Painter Operator', 59344);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (85, 'ECM Operator', 'ECM Operator', 59345);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (86, 'Sensor Dampener Operator', 'Sensor Dampener Operator', 59346);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (87, 'Tracking Disruptor Operator', 'Tracking Disruptor Operator', 59347);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (88, 'Propulsion Jammer Operator', 'Propulsion Jammer Operator', 59348);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (89, 'Interdiction Maneuvers', 'Interdiction Maneuvers', 59349);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (90, 'High-Velocity Helmsman', 'High-Velocity Helmsman', 59350);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (91, 'Cartographer', 'Cartographer', 59351);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (92, 'Wormhole Generation', 'Wormhole Generation', 59423);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (93, 'Unit Leader', 'Unit Leader', 59352);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (94, 'Tactical Commander', 'Tactical Commander', 59353);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (95, 'Battlespace Technician', 'Battlespace Technician', 59354);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (96, 'Armored Warfare Chief', 'Armored Warfare Chief', 59355);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (97, 'Information Warfare Chief', 'Information Warfare Chief', 59356);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (98, 'Siege Warfare Chief', 'Siege Warfare Chief', 59357);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (99, 'Skirmish Warfare Chief', 'Skirmish Warfare Chief', 59358);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (100, 'Fleet Co-Ordinator', 'Fleet Co-Ordinator', 59359);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (101, 'Harvesting Comptroller', 'Harvesting Comptroller', 59360);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (102, 'Resource Harvester', 'Resource Harvester', 59361);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (103, 'Mercoxit Specialist', 'Mercoxit Specialist', 59362);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (104, 'Industrial Harvesting', 'Industrial Harvesting', 59363);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (105, 'Ice Specialist', 'Ice Specialist', 59364);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (106, 'Automated Mining', 'Automated Mining', 59365);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (108, 'Refinery Foreman', 'Refinery Foreman', 59396);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (109, 'Common Ore Refiner', 'Common Ore Refiner', 59397);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (110, 'Rare Ore Refiner', 'Rare Ore Refiner', 59398);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (111, 'Production Intern', 'Production Intern', 59366);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (112, 'Production Manager', 'Production Manager', 59367);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (113, 'Research Manager', 'Research Manager', 59368);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (114, 'Field Technician', 'Field Technician', 59399);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (115, 'Business Mogul', 'Business Mogul', 59369);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (116, 'Business Tycoon', 'Business Tycoon', 59370);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (117, 'Remote Demolitions', 'Remote Demolitions', 59371);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (140, 'Colony Management', 'Colony Management', 59424);
INSERT INTO crtClasses (classID, className, description, classNameID) VALUES (141, 'Planetology', 'Planetology', 59425);
