# Generated by CacheToSQL on 20.04.2011 18:56:28 (UTC)
# Source: config.BulkData.paperdollModifierLocations

DROP TABLE IF EXISTS paperdollModifierLocations;
CREATE TABLE paperdollModifierLocations (
    modifierLocationID INT,
    modifierKey TEXT,
    variationKey TEXT,
    PRIMARY KEY (modifierLocationID)
);

INSERT INTO paperdollModifierLocations (modifierLocationID, modifierKey, variationKey) VALUES (2, 'topouter', 'dependants/drape');
INSERT INTO paperdollModifierLocations (modifierLocationID, modifierKey, variationKey) VALUES (3, 'makeup/implants', '');
INSERT INTO paperdollModifierLocations (modifierLocationID, modifierKey, variationKey) VALUES (4, 'accessories/earslow', '');
INSERT INTO paperdollModifierLocations (modifierLocationID, modifierKey, variationKey) VALUES (5, 'hair', '');
INSERT INTO paperdollModifierLocations (modifierLocationID, modifierKey, variationKey) VALUES (6, 'makeup/eyes', '');
INSERT INTO paperdollModifierLocations (modifierLocationID, modifierKey, variationKey) VALUES (7, 'makeup/lipstick', '');
INSERT INTO paperdollModifierLocations (modifierLocationID, modifierKey, variationKey) VALUES (8, 'makeup/blush', '');
INSERT INTO paperdollModifierLocations (modifierLocationID, modifierKey, variationKey) VALUES (9, 'makeup/eyeshadow', '');
INSERT INTO paperdollModifierLocations (modifierLocationID, modifierKey, variationKey) VALUES (10, 'outer', 'dependants/hood');
INSERT INTO paperdollModifierLocations (modifierLocationID, modifierKey, variationKey) VALUES (11, 'makeup/freckles', '');
INSERT INTO paperdollModifierLocations (modifierLocationID, modifierKey, variationKey) VALUES (12, 'accessories/nose', '');
INSERT INTO paperdollModifierLocations (modifierLocationID, modifierKey, variationKey) VALUES (13, 'accessories/nostril', '');
INSERT INTO paperdollModifierLocations (modifierLocationID, modifierKey, variationKey) VALUES (14, 'accessories/lips', '');
INSERT INTO paperdollModifierLocations (modifierLocationID, modifierKey, variationKey) VALUES (15, 'makeup/aging', '');
INSERT INTO paperdollModifierLocations (modifierLocationID, modifierKey, variationKey) VALUES (16, 'beard', '');
INSERT INTO paperdollModifierLocations (modifierLocationID, modifierKey, variationKey) VALUES (17, 'makeup/eyeliner', '');
INSERT INTO paperdollModifierLocations (modifierLocationID, modifierKey, variationKey) VALUES (18, 'makeup/eyelashes', '');
INSERT INTO paperdollModifierLocations (modifierLocationID, modifierKey, variationKey) VALUES (19, 'accessories/earshigh', '');
INSERT INTO paperdollModifierLocations (modifierLocationID, modifierKey, variationKey) VALUES (20, 'makeup/eyebrows', '');
INSERT INTO paperdollModifierLocations (modifierLocationID, modifierKey, variationKey) VALUES (21, 'accessories/glasses', '');
INSERT INTO paperdollModifierLocations (modifierLocationID, modifierKey, variationKey) VALUES (22, 'feet', '');
INSERT INTO paperdollModifierLocations (modifierLocationID, modifierKey, variationKey) VALUES (23, 'bottominner', '');
INSERT INTO paperdollModifierLocations (modifierLocationID, modifierKey, variationKey) VALUES (24, 'makeup/scarring', '');
INSERT INTO paperdollModifierLocations (modifierLocationID, modifierKey, variationKey) VALUES (25, 'bottomouter', 'dependants/boottucking');
INSERT INTO paperdollModifierLocations (modifierLocationID, modifierKey, variationKey) VALUES (26, 'topmiddle', 'dependants/drape');
INSERT INTO paperdollModifierLocations (modifierLocationID, modifierKey, variationKey) VALUES (27, 'topinner', '');
INSERT INTO paperdollModifierLocations (modifierLocationID, modifierKey, variationKey) VALUES (28, 'scars/head', '');
INSERT INTO paperdollModifierLocations (modifierLocationID, modifierKey, variationKey) VALUES (29, 'accessories/brow', '');
INSERT INTO paperdollModifierLocations (modifierLocationID, modifierKey, variationKey) VALUES (30, 'tattoo/head', '');
INSERT INTO paperdollModifierLocations (modifierLocationID, modifierKey, variationKey) VALUES (31, 'archetypes', '');
INSERT INTO paperdollModifierLocations (modifierLocationID, modifierKey, variationKey) VALUES (32, 'accessories/chin', '');
INSERT INTO paperdollModifierLocations (modifierLocationID, modifierKey, variationKey) VALUES (33, 'accessories', '');
INSERT INTO paperdollModifierLocations (modifierLocationID, modifierKey, variationKey) VALUES (34, 'accessories/piercings', '');
