//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVEMon.Common.Serialization.Datafiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DatafileConstants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DatafileConstants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EVEMon.Common.Serialization.Datafiles.DatafileConstants", typeof(DatafileConstants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eve-blueprints-en-US.xml.gz.
        /// </summary>
        public static string BlueprintsDatafile {
            get {
                return ResourceManager.GetString("BlueprintsDatafile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eve-certificates-en-US.xml.gz.
        /// </summary>
        public static string CertificatesDatafile {
            get {
                return ResourceManager.GetString("CertificatesDatafile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eve-geography-en-US.xml.gz.
        /// </summary>
        public static string GeographyDatafile {
            get {
                return ResourceManager.GetString("GeographyDatafile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eve-items-en-US.xml.gz.
        /// </summary>
        public static string ItemsDatafile {
            get {
                return ResourceManager.GetString("ItemsDatafile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eve-properties-en-US.xml.gz.
        /// </summary>
        public static string PropertiesDatafile {
            get {
                return ResourceManager.GetString("PropertiesDatafile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eve-reprocessing-en-US.xml.gz.
        /// </summary>
        public static string ReprocessingDatafile {
            get {
                return ResourceManager.GetString("ReprocessingDatafile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eve-skills-en-US.xml.gz.
        /// </summary>
        public static string SkillsDatafile {
            get {
                return ResourceManager.GetString("SkillsDatafile", resourceCulture);
            }
        }
    }
}
