

//***  initial greetings - positive
(236722, `Nice to see you, {[character]player.name}.`)
(236723, `I am exhilarated at seeing you, {[character]player.name}. I hope I can be of assistance.`)
(236724, `Nice to see you {[character]player.name}!`)
(236726, `{[character]player.name}! You're back! Please have a seat and make yourself feel comfortable. If there is anything you need, just ask.`)

//***  initial greetings - neutral
(236729, `Greetings, {[character]player.name}.`)
(236725, `Why hello there. What do you want?`)
(236778, `Why hello there.  What do you want?`)
(135808, 'How can I assist you? ')

//***  initial greetings - negative
(236727, `I hope you're not here to ask me for a favor. I hate beggars.`)
(236728, `What do you want? Spit it out, stooge.`)
(236788, `You've got a lot of nerve, showing your face around here.`)
(236786, `Begone, scum.`)

//***  initial greetings - no work
(236697, `I'm busy.  Go away.`)
(236699, `I'm busy, go away.`)
(236703, `Sorry, I have no jobs available for you.`)
(236779, `If you're here to find an excuse to show off those big, shiny weapons of yours, then I suggest you go find some nincompoop working for the {[npcOrganization]agentFactionID.name} military and leave me alone.  If not, then I might lend you an ear, depending on your worth to me.`)
(236780, `You just interrupted me from my studies.  This better be good ...`)
(236781, `I take it you are interested in scientific studies.  Perhaps I can be of assistance.`)
(236798, `Sorry, kid, nothing at the moment. Could you come back later?`)
(236799, `I'm sorry, but what I've got is promised to another pilot already. Could you come back later?`)
(129421, 'Who are you?  I've got important business to attend to, so unless you're somebody important get lost.')
(129422, 'Who are you?  I've got important business to attend to, so unless you're somebody important get lost.')

//***  initial greetings - no standing
(236682, `I’m sorry pilot, but you do not have the required standings to receive any missions from me. You will need to raise your standings by doing missions for lower-ranked agents. Use the Agent Finder to locate agents that are available to you.`)
(236691, `I’m sorry pilot, but you do not have the required standings to receive any missions from me. You will need to raise your standings by doing missions for lower-ranked agents. Use the Agent Finder to locate agents that are available to you.`)
(236708, `Trial account users cannot access agents of level 3 or higher. Either use your map settings to find a level 1 or level 2 agent, or consider purchasing an EVE subscription if you wish to access higher-level content.`)
(236785, `What planet were you born on?  Check your standings next time or I'll drill a hole in you.`)
(236787, `Have you even bothered to check your standings.`)
(236775, `Hello, {[character]player.name}.  I was given the assignment of handing out a valuable item to loyal supporters of {[npcOrganization]agentFactionID.name}.  If you know of someone who has proven him or herself time and time again for {[npcOrganization]agentFactionID.nameWithArticle} then point that person to me and perhaps we can come to an 'arrangement' ...<br><br>You on the other hand do not meet my requirements or have already received my offer.`)
(236853, `I’m sorry pilot, but you do not have the required standings to receive any missions from me. You will need to raise your standings by doing missions for lower-ranked agents. Use the Agent Finder to locate agents that are available to you.`)


//***  initial greetings - no reference/referral
(236692, `Get out of my sight, mortal.`)
(236681, `I will only give out missions to those who have joined the war!`)
(236686, `We're closed to the public.`)
(236689, `I'm sorry, but I have no business with you at the moment.  Come back once you have a referral.`)
(236696, `Sorry, but I only work with people I trust.  Come back once you have a referral.`)
(236713, `Sorry, I have no jobs for the general public.`)
(236770, `Sorry, I have no jobs for the general public.`)
(236774, `{agentFactionName} does not provide work to the general public.`)

//***  initial greetings - remote denied
(236687, `I'm sorry, what did you say? There's a bit of interference on the channel at the moment. Perhaps you could call back using a station line?`)
(236707, `I'm sorry, what did you say? There's a bit of interference on the channel at the moment. Perhaps you could call back using a station line?`)
(236719, `My offices are located at {[location]agentStationID.name}.  If you want to talk, please meet me in person.`)
(236717, `I am currently off in {[location]agentSolarSystemID.name}.  If you want to talk, please meet me in person.`)

//***  initial greetings - unfinished mission
(236730, `Nice to see you, {[character]player.name}, but you know you still have an unfinished mission from me, right?`)
(236731, `Always a pleasure, of course. But the last mission I gave you isn't going to complete itself.`)
(236732, `Hey, {[character]player.name}. I really like your style... but I do need you to finish up your current mission for me.`)
(236733, `{[character]player.name}! You're back! If there is anything you need, just ask. But you are going to finish your current mission, right?`)
(236734, `Great to see you, {[character]player.name}, as always. I have to assume there's a good reason that you've come back before finishing your current mission??`)
(236735, `You do know you haven't finished your current mission for me, right?`)
(236736, `{[character]player.name}, you need to finish your current mission for me.`)
(236737, `You need to finish your current mission. Don't talk to me until then.`)

//***  initial greetings - offered mission
(236803, `Yes my offer is still open.<br><br>{missionOfferText}`)

//***  initial greetings - available mission
(236804, `Yes, I have something for you.<br><br>{missionBriefingText}`)
(236805, `Sure I've got something.<br><br>{missionBriefingText}`)
(236806, `I have just the thing you want.<br><br>{missionBriefingText}`)
(236807, `Something just came up that's right up your alley.<br><br>{missionBriefingText}`)
(236808, `For you, my friend, there's always something.<br><br>{missionBriefingText}`)
(236809, `Here is a mission suited for someone of your caliber.<br><br>{missionBriefingText}`)


//***   mission accept msgs
(236738, `Very well then, get going.`)
(236739, `Ok, hurry up will you.`)
(236740, `Good good, now get out there and give me some results.`)
(236741, `Thank you, and good luck.`)
(236742, `Thanks, I really appreciate it.`)
(236743, `Have fun!`)
(236744, `Now be careful out there, you hear me?`)
(236745, `Stay alive, friend.`)
(236721, `You have a long and prosperous future within {[npcOrganization]agentFactionID.name}, {[character]player.name}.`)
(236746, `I knew I could count on you.`)
(236747, `Great.  I know I can trust you with this, mate.`)
(236748, `Stay alive, friend.`)
(236749, `Wonderful.  I expect a quick result with you on the job.`)
(135877, 'I knew we could count on you, {[character]player.name}. Please hurry. ')


//***  mission quit msgs
(135862, 'I've changed my mind — these odds are too uncertain. I quit. ')
(133434, 'I’m gonna have to call it quits on this mission, {[character]agentID.name}. Sorry. ')
(137518, 'Oh…sorry, I won’t be able to leave immediately. You better find someone else.')
(137519, 'I’m afraid I can’t make it out to them after all. Sorry for the let down.')
(135853, 'You know, this sounds pretty risky. And I just had my ship cleaned and repainted. Nah, I'm gonna pass, thanks. ')
(135861, 'Sorry, but I can't do it, {[character]agentID.name}. Pressing business elsewhere. ')
(236846, `Quitters never win.`)

//***  mission decline msgs
(236693, `It's your loss.`)
(236695, `Son, I am disappoint.`)
(236793, `Too bad, I'll try to find someone else then for that job.`)
(236794, `Bah, that mission wasn't that bad. Oh well, wait a bit and I'll come up with something else.`)
(236795, `It's your loss.`)
(236796, `Well, don't expect me to come up with something as good later on.`)
(236797, `Your wayward ways displease me.`)
(236801, `It's your loss.`)
(236802, `Your wayward ways displease me, young one.`)
(236843, `See if I offer this to you again... seriously try it.`)
(236844, `Hey, hey, listen!`)
(130895, 'Fine.  Be that way.  Asshole.')
(133432, 'Too bad, {[character]player.name}. You could have made some serious points with the powers-that-be on this one. ')
(135858, 'I'm sorry to hear that, {[character]player.name}. I'll find someone else, I suppose.')
(135895, 'Lollygagger')
(136319, 'Hm… not really into playing courier, no. Sorry. I'll look for something else. ')
(136322, 'I see. Easy money's not good enough, eh? Huh. ')
(137496, 'Sorry, this doesn’t interest me one bit.   ')
(137499, 'Fine, I’ll get someone more capable. A word of advice: don’t repeat this display of cowardice and uselessness. We don’t tolerate such things in the Republic.  ')
(137502, 'Sorry, this doesn’t interest me one bit.   ')

//*** mission failed msgs
(236845, `You have failed me for the last time.`)
(236800, `I had a hunch you wouldn't pull through.`)
(130896, 'You suck.')

//***  mission complete msgs
(236750, `Fabulous.  I couldn't have asked for a better man for the job.`)
(236751, `Not bad.  Get back to me later for another assignment will you?`)
(236752, `Nice work.  I'm starting to like your style.`)
(236753, `Thanks, your services to {[npcOrganization]agentCorpID.name} is duly appreciated.`)
(236754, `Thank you.  Your accomplishment has been noted and saved into our database.`)
(236755, `Excellent job!`)
(236756, `Thanks, I really appreciate your help.`)
(236757, `I won't forget this.`)
(236758, `I'm grateful for your assistance.`)
(236759, `You have my gratitude.`)
(236760, `Thank you very much, I really appreciate it.`)
(236761, `Well done!  Take this reward and my gratitude as well.`)
(236762, `It's a pleasure doing business with you.`)
(236763, `Excellent work!  Care for another assignment?`)
(236764, `I look forward to your next visit.`)
(236765, `Again you finish the job right on time.  Keep this up and I'll probably get a promotion.`)
(236766, `I thank you from the bottom of my heart.`)
(236767, `If only I had more excellent pilots like you, {[character]player.name} ...`)
(236768, `Your talents as a pilot never cease to amaze me.  Keep up the good work!`)
(139398, 'I knew you were the right pilot for the job.')

(137501, 'Don’t worry, I won’t let you down. ')
(236782, `Ah, how lucky I am to see you again!  Then again, luck is an expression for the simple minded, as all occurances can easily be explained with mathematical calculations.
Oh what am I rambling about, please have a seat and tell me what is on your mind.`)
(236783, `Welcome, fellow colleague.  I guess you came to discuss my new theory on quantum mechanics, or are you here on other business?`)
(236784, `It's always a pleasure meeting you, {[character]player.name}.  I suppose you are here for some research, or some work perhaps?`)
(236688, `Sure.`)
(236690, `A wise decision.`)
(236701, `Oh my! My computer just crashed horribly when I was entering your mission acceptance, and I lost the file on your mission.
I knew I should have installed a backup file system... Anyhow, the cause of this has been logged on the server along with a nice stack trace explaining what went wrong,
 so the proper authorities will undoubtedly repair this mission as soon as possible. Perhaps you would like another mission in the meantime?`)
(236702, `Sounds good. Please drop by, so we can formalize the mission contract.`)
(236706, `Thanks dude, I owe you one.`)
(236710, `Your generosity astounds me, but I could never forgive myself for taking more of your money so soon.`)
(236712, `Great! Please drop by, so we can formalize the mission contract.`)
(236715, `You don't have the items I required at {[location]agentStationID.name}.  The item(s) must be located in your cargo hold or in your personal hangar.  If you have multiple objectives of the same item type in the same location, please use either the hangar or your cargo hold, but not both.  If a specific item was requested as opposed to any item of the specified type, please be sure that the correct specific item is indeed being provided.  Otherwise, please make sure that the item is not assembled, packaged or damaged.  Check the journal for more detail`)
(236716, `You don't have the items I required in {[location]agentSolarSystemID.name}.  The item(s) must be located in your cargo hold.  If a specific item was requested as opposed to any item of the specified type, please be sure that the correct specific item is indeed being provided.  Otherwise, please make sure that the item is not assembled, packaged or damaged.  Check the journal for more detail`)
(236718, `Hello {[character]player.name}. Good to see you again. I would like to remind you that you have previously completed this epic arc and for you to embark on it once again I would have to erase all memory of the arc from your mind. Are you sure you would like to start this journey once again and lose all history of this arc?`)
(236720, `So you think you're tough? If that's the case, I might have some use for you.`)
(236769, `I am in your debt {[character]player.name}.  If you ever need anything, just look me up.`)
(236776, `You haven't heard? Gigantic harvestable gas clouds have been discovered here in {[location]agentConstellationID.name}! All you need is a Gas Cloud Harvester module and the persistence to find one of these clouds and you'll make a fortune! And if you have a Starbase or Outpost nearby, you might even be able to create valuable boosters out of the chemicals. Well, as long as you have a blueprint.<br><br>I've managed to bribe the local pirate captains so that they'll leave me alone, but I'm worried about going deeper into {[location]agentConstellationID.name}. It's pretty dangerous out there.`)
(236777, `I take it you are back for some more research?  If so then I'll see if I can assist you.`)
(236789, `{missionCompletionText}<br><br>By the way, I have another mission prepared for you already...`)
(236790, `I don't know you well enough to accept your money. Try seeking out an agent further down the corporate ladder until your standings have improved.`)
(236791, `Your money isn't good enough. Try seeking out an agent further down the corporate ladder until your standings have improved.`)
(236792, `Nobody sent you? I only work with people I trust. Talk to one of my subordinates until your standings have improved.`)

(236810, `Come to do a little research eh?  I'm a busy {[character]agentID.gender -> "man", "girl"}, but I guess I can spare a few moments of my time.`)
(236811, `Good job!  I don't know how we'd be able to complete this research project without you!`)
(236812, `Nice work.  Our research will definitely benefit from this.`)

(236827, `What was that? I did not get your last transmission`)
(236828, `I don't have any more datacores to sell for now. You should try again tomorrow.`)
(236831, `I hope those datacores will come in handy for you`)
(236841, `I was sure that would break somewhere along the way.`)
(236842, `I'm willing to give you another chance to <b>NOT</b> screw things up.`)
(236874, `With you and me working together, I'm sure there will be marvelous breakthroughs.`)
(236875, `You don't have sufficient skill as a Research Project Manager to handle any more research projects.`)
(236876, `You don't have the skills to match mine.`)
(236877, `I'm sorry you feel that way, but alas, our research hadn't gotten anywhere yet so no harm done.`)
(236924, `Are you sure you want to cancel your current research project?  All your points will be lost and you will quit the current mission you have with this agent.`)
(236925, `Are you sure you want to cancel your current research project?  All your points will be lost.`)
(263558, `I can no longer await your response to my offer. I am displeased by your indecisiveness.`)
(263559, `Mission Offer Expired`)

(135333, 'Too. Many. Rocks. Uhhhh… <br><br>I quit.')
(135334, 'What kind of miner are you?')
(135335, 'I can harvest the cloud for you.')
(135336, 'Thank you. You wouldn't believe how difficult it is to find a good gas harvester around here.')

(129423, 'I'm just here for some work.')
(129424, 'I think I have something that would interest you.')

(130890, 'Hey test dummy, gimme a mission right now!')
(130897, 'I'm lookin' for some work. You got any?')
(130904, 'So what's next? You seem like you have something on your mind.')
(130905, 'Yes, thanks for the help, {[character]player.name}. Wish I could find more for you to do right now, but most of the jobs around here are beneath a capsuleer like you. ')
(130906, 'I guess my work here is done.')
(130907, 'You need any help?')

(133433, 'Glad to be here. So I assume there’s something I can help you out with?')

(135824, 'Let me at 'em! ')
(135825, 'That was fun. ')
(135826, 'Nothing I'd enjoy more…')
(135854, 'Hey, I'm all about dealing with pirates. What's the problem?')
(135855, 'I guess you can't take the heat. There are others who will. ')
(135856, 'Good hunting, my friend.')
(135857, 'Excellent work! That'll put the fear of their bloodthirsty god right into them. ')
(135859, 'Sounds like quite a challenge. Sure, I'll help. ')
(135863, 'Good day, {[character]agentID.name}. What can you offer me? ')
(135878, 'Good job! We've scored a major victory here, thanks to you! ')
(135879, 'Damnation, {[character]player.name}! You were our best hope. I just pray I can find someone else. ')
(135880, 'It sounds like a very difficult job. Of course I'll do it! ')
(135905, 'Always happy to help, but especially when there's ISK involved. ')
(136067, 'Give me something meaningful to do, {[character]agentID.name}. I’m looking for a challenge.')

(136295, 'Excellent. You're doing us a great service, {[character]player.name}. ')
(136318, 'Actually, the question is, can I help you? {[character]player.name}, capsuleer, at your service. ')
(136321, 'Oh, sure. Nice, easy work, with good pay? I'm all for that. ')
(136323, 'I expect so, yeah. And thanks. Just give me a few minutes to pull up my files, will you? ')
(136324, 'Excellent. I've just uploaded the coordinates of the pickup station to your NeoCom. Do be quick, okay? ')
(136636, '{[character]player.name}, recent graduate and capsuleer. And looking for work. ')
(136647, 'Well, that's easy enough. Sure, I can do that. ')
(136648, 'Yes, there is. Come on back to my office and we'll discuss it there in private, though, okay? ')
(136649, 'Thanks. I'll see you when you get back. ')
(137497, 'That’s why I’m here. What’s the problem?')
(137498, 'A troubling individualism')
(137500, 'See that you do not.')
(137520, 'I’ve come for work, yes.')
(139117, 'Oh, so I suppose you want to do something a little less dangerous?')
(139118, 'Or were you just too busy watching vids?')
(139119, 'Had to send someone else. Sorry, chump.   ')
(139120, 'No guts, huh?')
(139121, 'Hey.')
(139122, 'Hell yeah, let me at ‘em!')
(139124, 'Sounds risky. I think I'll pass.')
(139125, 'This is too much work. Find some other chump.')
(139126, 'That depends. You got something interesting for me?')
(139127, 'I just might be, yes. What have you got? ')
(139128, 'I’m taking more damage than I expected. I need to bail out of this mission, {[character]agentID.name}. Sorry. ')
(139129, 'Doesn’t interest me. Sorry.')
(139134, 'I... <i>we</i> appreciate your assistance. ')
(139135, 'This isn’t going to look good to my superiors, {[character]player.name}, but I accept your decision. ')
(139155, 'Oh, so I suppose you want to do something a little less dangerous?')
(139156, 'People were counting on you! ')
(139157, 'I’ll just get someone who has some balls, then.')
(139162, 'Sounds risky. I'll pass.')
(139163, 'Okay, this is a bit much. I’m gonna have to quit.')
(139164, 'You need something handled?')
(139165, 'You know what they say about <i>assumptions,</i> right? …something about, uh, sums and options… I think. <br><br>
Why am I here again?
')
(139166, 'Hey, I didn't sign up for <i>this</i> when I accepted your mission! ')
(139167, 'Wow, you know, I have something more important to do. Like... uh... yeah — no thanks. ')
(139202, 'Your loss, {[character]player.name}.')
(139203, 'Sure, I’ll give it a shot, {[character]agentID.name}. When do I leave?')
(139204, 'You were <i>definitely</i> low-balling the risk, {[character]agentID.name}. Here's your precious container.')
(139205, 'I think you’re low-balling the risk here. I’ll look for opportunities elsewhere.')
(139206, 'Holy crap, where are all those ships coming from? I’m taking too much damage. I quit!')
(139207, 'I've been busy. What've you got cooking? ')
(139208, 'Really? You can't? I would never have guessed. ')
(139212, 'At last, something interesting! I'll do it!')
(139264, 'Of course I’ll do it.')
(139286, 'I see.  Well, perhaps you will be of some use next time.')
(139287, 'I see.  Well, perhaps you will be of some use next time.')
(139321, 'Might be, {[character]agentID.name}. What have you got? ')
(139325, 'Sounds like a decent job. I’ll do it.')
(139326, 'That’s too bad, {[character]player.name}. Nothing else available right now, I’m afraid. ')
(139327, 'Your assistance is appreciated, {[character]player.name}. ')
(139406, 'You can count on me.')
(139398, 'I knew you were the right pilot for the job.')
(139400, 'You are not the pilot I thought you were. I'll be sure to spread the word of your laziness and ingratitude.')
(235462, 'Your personal standings must be -1.9 or higher toward this agent, its faction, or its corporation in order to use this agent's services.')
(235463, 'Your personal standings must be -1.9 or higher toward this agent, its faction, and its corporation in order to use this agent's services. Additionally, you need a minimum effective standing to this agent's corp of at least {[numeric]corpMinStandings, decimalPlaces=1} , as well as personal standing of at least {[numeric]effectiveMinStandings, decimalPlaces=1} to this agent's faction, corp, or to the agent in order to use this agent's services.')
(235464, 'Your personal standings must be -1.9 or higher toward this agent, its faction, and its corporation in order to use this agent's services. Additionally, you need a minimum effective standing of at least {[numeric]minStandings, decimalPlaces=1} to this agent's faction, corp, or to the agent in order to use this agent's services.')
(235465, 'Your effective personal standings must be {[numeric]minStandings, decimalPlaces=1} or higher toward this agent, its faction, or its corporation in order to use this agent's services')
(235466, 'Your effective personal standings must be {[numeric]minEffective, decimalPlaces=1} or higher toward this agent's corporation in order to use this agent, as well as an effective personal standing of {[numeric]mainEffective, decimalPlaces=1} or higher toward this agent, its faction, or its corporation in order to use this agent's services.')
(235467, 'This agent can only be used through a direct referral.')

(236845, 'You have failed me for the last time.')
(236846, 'Quitters never win.')
(135816, 'I'm always ready to help. What's going on? ')
(135817, 'See you when you return, my friend.')
(135818, 'You're a hell of a pilot, {[character]player.name}. Come back in a bit and I'll let you know if there's more work for you.')
(135811, 'Move quickly, {[character]player.name}. ')
(133764, 'Thanks and good luck, {[character]player.name}. ')
(133765, 'Good work, {[character]player.name}. ')
(133777, 'How can I help, {[character]agentID.name}?')
(135137, 'Sure. I'll see what I can do.')
(135138, 'Don't waste any time. Our people are waiting.')
(135139, 'I'm ready. What's up?')
(135141, 'Nice work. I'll keep you in mind when something else comes up.')
(135142, 'I hope I can find someone else to handle this.')
(135144, 'Maybe next time, huh? In any case, {[npcOrganization]agentCorpID.name} will manage. It's your loss. ')



{'FullPath': u'UI/Agents/DefaultMessages/RootAgentSays', 'messageID': 236720, 'label': u'Medium1'}(u"So you think you're tough? If that's the case, I might have some use for you.", None, None)
{'FullPath': u'UI/Agents/DefaultMessages/RootAgentSays', 'messageID': 236721, 'label': u'High1'}(u'You have a long and prosperous future within {[npcOrganization]agentFactionID.name}, {[character]player.name}.', None, {u'{[character]player.name}': {'conditionalValues': [], 'variableType': 0, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'player'}, u'{[npcOrganization]agentFactionID.name}': {'conditionalValues': [], 'variableType': 1, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'agentFactionID'}})
{'FullPath': u'UI/Agents/DefaultMessages/RootAgentSays', 'messageID': 236722, 'label': u'Medium2'}(u'Nice to see you, {[character]player.name}.', None, {u'{[character]player.name}': {'conditionalValues': [], 'variableType': 0, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'player'}})
{'FullPath': u'UI/Agents/DefaultMessages/RootAgentSays', 'messageID': 236723, 'label': u'High4'}(u'I am exhilarated at seeing you, {[character]player.name}. I hope I can be of assistance.', None, {u'{[character]player.name}': {'conditionalValues': [], 'variableType': 0, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'player'}})
{'FullPath': u'UI/Agents/DefaultMessages/RootAgentSays', 'messageID': 236724, 'label': u'High3'}(u'Nice to see you {[character]player.name}!', None, {u'{[character]player.name}': {'conditionalValues': [], 'variableType': 0, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'player'}})
{'FullPath': u'UI/Agents/DefaultMessages/RootAgentSays', 'messageID': 236725, 'label': u'Low1'}(u'Why hello there. What do you want?', None, None)
{'FullPath': u'UI/Agents/DefaultMessages/RootAgentSays', 'messageID': 236726, 'label': u'High2'}(u"{[character]player.name}! You're back! Please have a seat and make yourself feel comfortable. If there is anything you need, just ask.", None, {u'{[character]player.name}': {'conditionalValues': [], 'variableType': 0, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'player'}})
{'FullPath': u'UI/Agents/DefaultMessages/RootAgentSays', 'messageID': 236727, 'label': u'Low3'}(u"I hope you're not here to ask me for a favor. I hate beggars.", None, None)
{'FullPath': u'UI/Agents/DefaultMessages/RootAgentSays', 'messageID': 236728, 'label': u'Low2'}(u'What do you want? Spit it out, stooge.', None, None)
{'FullPath': u'UI/Agents/DefaultMessages/RootAgentSays', 'messageID': 236729, 'label': u'GenericGreetings'}(u'Greetings, {[character]player.name}.', None, {u'{[character]player.name}': {'conditionalValues': [], 'variableType': 0, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'player'}})
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236730, 'label': u'RootMissionInProgressMedium1'}(u'Nice to see you, {[character]player.name}, but you know you still have an unfinished mission from me, right?', None, {u'{[character]player.name}': {'conditionalValues': [], 'variableType': 0, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'player'}})
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236731, 'label': u'RootMissionInProgressMedium2'}(u"Always a pleasure, of course. But the last mission I gave you isn't going to complete itself.", None, None)
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236732, 'label': u'RootMissionInProgressMedium3'}(u'Hey, {[character]player.name}. I really like your style... but I do need you to finish up your current mission for me.', None, {u'{[character]player.name}': {'conditionalValues': [], 'variableType': 0, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'player'}})
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236733, 'label': u'RootMissionInProgressHigh1'}(u"{[character]player.name}! You're back! If there is anything you need, just ask. But you are going to finish your current mission, right?", None, {u'{[character]player.name}': {'conditionalValues': [], 'variableType': 0, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'player'}})
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236734, 'label': u'RootMissionInProgressHigh2'}(u"Great to see you, {[character]player.name}, as always. I have to assume there's a good reason that you've come back before finishing your current mission??", None, {u'{[character]player.name}': {'conditionalValues': [], 'variableType': 0, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'player'}})
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236735, 'label': u'RootMissionInProgressLow1'}(u"You do know you haven't finished your current mission for me, right?", None, None)
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236736, 'label': u'RootMissionInProgressLow3'}(u'{[character]player.name}, you need to finish your current mission for me.', None, {u'{[character]player.name}': {'conditionalValues': [], 'variableType': 0, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'player'}})
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236737, 'label': u'RootMissionInProgressLow2'}(u"You need to finish your current mission. Don't talk to me until then.", None, None)
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236738, 'label': u'MissionAcceptedLow1'}(u'Very well then, get going.', None, None)
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236739, 'label': u'MissionAcceptedLow2'}(u'Ok, hurry up will you.', None, None)
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236740, 'label': u'MissionAcceptedLow3'}(u'Good good, now get out there and give me some results.', None, None)
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236741, 'label': u'MissionAcceptedLowMed1'}(u'Thank you, and good luck.', None, None)
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236742, 'label': u'MissionAcceptedLowMed2'}(u'Thanks, I really appreciate it.', None, None)
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236743, 'label': u'MissionAcceptedLowMed3'}(u'Have fun!', None, None)
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236744, 'label': u'MissionAcceptedLowMed4'}(u'Now be careful out there, you hear me?', None, None)
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236745, 'label': u'MissionAcceptedMedHigh1'}(u'Stay alive, friend.', None, None)
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236746, 'label': u'MissionAcceptedMedHigh2'}(u'I knew I could count on you.', None, None)
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236747, 'label': u'MissionAcceptedMedHigh3'}(u'Great.  I know I can trust you with this, mate.', None, None)
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236748, 'label': u'MissionAcceptedHigh1'}(u'Stay alive, friend.', None, None)
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236749, 'label': u'MissionAcceptedHigh2'}(u'Wonderful.  I expect a quick result with you on the job.', None, None)
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236750, 'label': u'MissionAcceptedHigh3'}(u"Fabulous.  I couldn't have asked for a better man for the job.", None, None)
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236751, 'label': u'MissionCompletedLow1'}(u'Not bad.  Get back to me later for another assignment will you?', None, None)
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236752, 'label': u'MissionCompletedLow2'}(u"Nice work.  I'm starting to like your style.", None, None)
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236753, 'label': u'MissionCompletedLow3'}(u'Thanks, your services to {[npcOrganization]agentCorpID.name} is duly appreciated.', None, {u'{[npcOrganization]agentCorpID.name}': {'conditionalValues': [], 'variableType': 1, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'agentCorpID'}})
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236754, 'label': u'MissionCompletedLowMed1'}(u'Thank you.  Your accomplishment has been noted and saved into our database.', None, None)
{'FullPath': u'Notifications', 'messageID': 236067, 'label': u'bodyCorpAppRejected'}(u'Dear {[character]charID.name}. Your application to join <b>{corporationName}</b> has been REJECTED.\n<br>\n<br>\n{applicationText}', None, {u'{corporationName}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'corporationName'}, u'{applicationText}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'applicationText'}, u'{[character]charID.name}': {'conditionalValues': [], 'variableType': 0, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'charID'}})
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236756, 'label': u'MissionCompletedLowMed3'}(u'Thanks, I really appreciate your help.', None, None)
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236757, 'label': u'MissionCompletedLowMed4'}(u"I won't forget this.", None, None)
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236758, 'label': u'MissionCompletedLowMed5'}(u"I'm grateful for your assistance.", None, None)
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236759, 'label': u'MissionCompletedLowMed6'}(u'You have my gratitude.', None, None)
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236760, 'label': u'MissionCompletedMedHigh1'}(u'Thank you very much, I really appreciate it.', None, None)
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236761, 'label': u'MissionCompletedMedHigh2'}(u'Well done!  Take this reward and my gratitude as well.', None, None)
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236762, 'label': u'MissionCompletedMedHigh3'}(u"It's a pleasure doing business with you.", None, None)
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236763, 'label': u'MissionCompletedMedHigh4'}(u'Excellent work!  Care for another assignment?', None, None)
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236764, 'label': u'MissionCompletedMedHigh5'}(u'I look forward to your next visit.', None, None)
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236765, 'label': u'MissionCompletedMedHigh6'}(u"Again you finish the job right on time.  Keep this up and I'll probably get a promotion.", None, None)
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236766, 'label': u'MissionCompletedHigh1'}(u'I thank you from the bottom of my heart.', None, None)
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236767, 'label': u'MissionCompletedHigh2'}(u'If only I had more excellent pilots like you, {[character]player.name} ...', None, {u'{[character]player.name}': {'conditionalValues': [], 'variableType': 0, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'player'}})
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236768, 'label': u'MissionCompletedHigh3'}(u'Your talents as a pilot never cease to amaze me.  Keep up the good work!', None, None)
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236769, 'label': u'MissionCompletedHigh4'}(u'I am in your debt {[character]player.name}.  If you ever need anything, just look me up.', None, {u'{[character]player.name}': {'conditionalValues': [], 'variableType': 0, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'player'}})
{'FullPath': u'UI/Agents/Storyline', 'messageID': 236770, 'label': u'StorylineNoneConfiggedGeneral'}(u'Sorry, I have no jobs for the general public.', None, None)
{'FullPath': u'UI/Agents/Storyline', 'messageID': 236774, 'label': u'StorylineNoneConfiggedFaction'}(u'{agentFactionName} does not provide work to the general public.', None, {u'{agentFactionName}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'agentFactionName'}})
{'FullPath': u'UI/Agents/DefaultMessages/RootAgentSays', 'messageID': 236775, 'label': u'ImprovingRelationsOverride'}(u"Hello, {[character]player.name}.  I was given the assignment of handing out a valuable item to loyal supporters of {[npcOrganization]agentFactionID.name}.  If you know of someone who has proven him or herself time and time again for {[npcOrganization]agentFactionID.nameWithArticle} then point that person to me and perhaps we can come to an 'arrangement' ...<br><br>You on the other hand do not meet my requirements or have already received my offer.", None, {u'{[npcOrganization]agentFactionID.nameWithArticle}': {'conditionalValues': [], 'variableType': 1, 'propertyName': 'nameWithArticle', 'args': 0, 'kwargs': {}, 'variableName': 'agentFactionID'}, u'{[character]player.name}': {'conditionalValues': [], 'variableType': 0, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'player'}, u'{[npcOrganization]agentFactionID.name}': {'conditionalValues': [], 'variableType': 1, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'agentFactionID'}})
{'FullPath': u'UI/Agents/DefaultMessages/RootAgentSays', 'messageID': 236776, 'label': u'BoosterManufacturingOverride'}(u"You haven't heard? Gigantic harvestable gas clouds have been discovered here in {[location]agentConstellationID.name}! All you need is a Gas Cloud Harvester module and the persistence to find one of these clouds and you'll make a fortune! And if you have a Starbase or Outpost nearby, you might even be able to create valuable boosters out of the chemicals. Well, as long as you have a blueprint.<br><br>I've managed to bribe the local pirate captains so that they'll leave me alone, but I'm worried about going deeper into {[location]agentConstellationID.name}. It's pretty dangerous out there.", None, {u'{[location]agentConstellationID.name}': {'conditionalValues': [], 'variableType': 3, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'agentConstellationID'}})
{'FullPath': u'UI/Agents/DefaultMessages/RootAgentSays', 'messageID': 236777, 'label': u'ResearchHigh2'}(u"I take it you are back for some more research?  If so then I'll see if I can assist you.", None, None)
{'FullPath': u'UI/Agents/DefaultMessages/RootAgentSays', 'messageID': 236778, 'label': u'ResearchLow1'}(u'Why hello there.  What do you want?', None, None)
{'FullPath': u'UI/Agents/DefaultMessages/RootAgentSays', 'messageID': 236779, 'label': u'ResearchLow5'}(u"If you're here to find an excuse to show off those big, shiny weapons of yours, then I suggest you go find some nincompoop working for the {[npcOrganization]agentFactionID.name} military and leave me alone.  If not, then I might lend you an ear, depending on your worth to me.", None, {u'{[npcOrganization]agentFactionID.name}': {'conditionalValues': [], 'variableType': 1, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'agentFactionID'}})
{'FullPath': u'UI/Agents/DefaultMessages/RootAgentSays', 'messageID': 236780, 'label': u'ResearchLow4'}(u'You just interrupted me from my studies.  This better be good ...', None, None)
{'FullPath': u'UI/Agents/DefaultMessages/RootAgentSays', 'messageID': 236781, 'label': u'ResearchLow3'}(u'I take it you are interested in scientific studies.  Perhaps I can be of assistance.', None, None)
{'FullPath': u'UI/Agents/DefaultMessages/RootAgentSays', 'messageID': 236782, 'label': u'ResearchHigh1'}(u'Ah, how lucky I am to see you again!  Then again, luck is an expression for the simple minded, as all occurances can easily be explained with mathematical calculations. Oh what am I rambling about, please have a seat and tell me what is on your mind.', None, None)
{'FullPath': u'UI/Agents/DefaultMessages/RootAgentSays', 'messageID': 236783, 'label': u'ResearchHigh3'}(u'Welcome, fellow colleague.  I guess you came to discuss my new theory on quantum mechanics, or are you here on other business?', None, None)
{'FullPath': u'UI/Agents/DefaultMessages/RootAgentSays', 'messageID': 236784, 'label': u'ResearchHigh4'}(u"It's always a pleasure meeting you, {[character]player.name}.  I suppose you are here for some research, or some work perhaps?", None, {u'{[character]player.name}': {'conditionalValues': [], 'variableType': 0, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'player'}})
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236785, 'label': u'RootStandingsTooLow4'}(u"What planet were you born on?  Check your standings next time or I'll drill a hole in you.", None, None)
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236786, 'label': u'RootStandingsTooLow1'}(u'Begone, scum.', None, None)
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236787, 'label': u'RootStandingsTooLow3'}(u'Have you even bothered to check your standings.', None, None)
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236788, 'label': u'RootStandingsTooLow2'}(u"You've got a lot of nerve, showing your face around here.", None, None)
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236789, 'label': u'MissionCompletedNextMission'}(u'{missionCompletionText}\n<br><br>\nBy the way, I have another mission prepared for you already...', None, {u'{missionCompletionText}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'missionCompletionText'}})
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236790, 'label': u'DonationsTooLowStandings1'}(u"I don't know you well enough to accept your money. Try seeking out an agent further down the corporate ladder until your standings have improved.", None, None)
{'FullPath': u'Notifications', 'messageID': 236073, 'label': u'subjSovCorporationClaimLost'}(u'Lost sovereignty in system {[location]solarSystemID.name}.', None, {u'{[location]solarSystemID.name}': {'conditionalValues': [], 'variableType': 3, 'propertyName': 'name', 'args': 0, 'kwargs': {}, 'variableName': 'solarSystemID'}})
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236792, 'label': u'DonationsTooLowStandings3'}(u'Nobody sent you? I only work with people I trust. Talk to one of my subordinates until your standings have improved.', None, None)
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236793, 'label': u'MissionDeclined1'}(u"Too bad, I'll try to find someone else then for that job.", None, None)
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236794, 'label': u'MissionDeclined2'}(u"Bah, that mission wasn't that bad. Oh well, wait a bit and I'll come up with something else.", None, None)
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236795, 'label': u'MissionDeclined3'}(u"It's your loss.", None, None)
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236796, 'label': u'MissionDeclined4'}(u"Well, don't expect me to come up with something as good later on.", None, None)
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236797, 'label': u'MissionDeclined5'}(u'Your wayward ways displease me.', None, None)
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236798, 'label': u'NoMission1'}(u'Sorry, kid, nothing at the moment. Could you come back later?', None, None)
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236799, 'label': u'NoMission2'}(u"I'm sorry, but what I've got is promised to another pilot already. Could you come back later?", None, None)
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236800, 'label': u'MissionQuitted1'}(u"I had a hunch you wouldn't pull through.", None, None)
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236801, 'label': u'MissionQuitted2'}(u"It's your loss.", None, None)
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236802, 'label': u'MissionQuitted3'}(u'Your wayward ways displease me, young one.', None, None)
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236803, 'label': u'OfferStillOpen'}(u'Yes my offer is still open.\n<br><br>\n{missionOfferText}', None, {u'{missionOfferText}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'missionOfferText'}})
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236804, 'label': u'MissionOffer1'}(u'Yes, I have something for you.<br><br>{missionBriefingText}', None, {u'{missionBriefingText}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'missionBriefingText'}})
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236805, 'label': u'MissionOffer2'}(u"Sure I've got something.<br><br>{missionBriefingText}", None, {u'{missionBriefingText}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'missionBriefingText'}})
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236806, 'label': u'MissionOffer3'}(u'I have just the thing you want.<br><br>{missionBriefingText}', None, {u'{missionBriefingText}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'missionBriefingText'}})
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236807, 'label': u'MissionOffer4'}(u"Something just came up that's right up your alley.<br><br>{missionBriefingText}", None, {u'{missionBriefingText}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'missionBriefingText'}})
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236808, 'label': u'MissionOffer5'}(u"For you, my friend, there's always something.<br><br>{missionBriefingText}", None, {u'{missionBriefingText}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'missionBriefingText'}})
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236809, 'label': u'MissionOffer6'}(u'Here is a mission suited for someone of your caliber.<br><br>{missionBriefingText}', None, {u'{missionBriefingText}': {'conditionalValues': [], 'variableType': 10, 'propertyName': None, 'args': 0, 'kwargs': {}, 'variableName': 'missionBriefingText'}})
{'FullPath': u'UI/Agents/DefaultMessages/RootAgentSays', 'messageID': 236810, 'label': u'ResearchLow2'}(u'Come to do a little research eh?  I\'m a busy {[character]agentID.gender -> "man", "girl"}, but I guess I can spare a few moments of my time.', None, {u'{[character]agentID.gender -> "man", "girl"}': {'conditionalValues': [u'man', u'girl'], 'variableType': 0, 'propertyName': 'gender', 'args': 64, 'kwargs': {}, 'variableName': 'agentID'}})
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236811, 'label': u'MissionCompletedResearch1'}(u"Good job!  I don't know how we'd be able to complete this research project without you!", None, None)
{'FullPath': u'UI/Agents/DefaultMessages', 'messageID': 236812, 'label': u'MissionCompletedResearch2'}(u'Nice work.  Our research will definitely benefit from this.', None, None)
