
CXXFLAGS=$(CXXFLAGS_COMMON) -I/usr/local/mysql/include -DFREEBSD
LDFLAGS=-lpcap -lz -O2 -ggdb -pipe -ldl -lpthread \
  -L/usr/local/mysql/lib -lmysqlclient

everything:
	$(MAKE) -f Makefile.darwin -C ../xmlpktgen
	$(MAKE) all

include .depend

include Makefile.common


