if(NOT DEFINED SOURCE OR NOT DEFINED DESTINATION_DIR)
  message(FATAL_ERROR "SOURCE and DESTINATION_DIR are required")
endif()

get_filename_component(FILE_NAME "${SOURCE}" NAME)
set(DESTINATION "${DESTINATION_DIR}/${FILE_NAME}")

if(NOT EXISTS "${DESTINATION}")
  file(COPY "${SOURCE}" DESTINATION "${DESTINATION_DIR}")
endif()
