
CXXFLAGS=-ggdb -O -pipe -Wall -I../common -I/usr/local/mysql/include \
  -I. -fno-inline -I/usr/include/python2.3 \
  -I../libs/libnids/src -DFREEBSD
LDFLAGS=-lpcap -lz -O2 -ggdb -pipe -ldl -lpthread \
  -L../libs/libnids/src -lnids \
  -L../libs/libnet/src -lnet \
  -L/usr/local/mysql/lib -lmysqlclient

everything: all

include .depend

include Makefile.common

