-- MySQL dump 10.13  Distrib 5.1.41, for debian-linux-gnu (x86_64)
--
-- Host: localhost    Database: evemu
-- ------------------------------------------------------
-- Server version	5.1.41-3ubuntu12.10

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `liveupdates`
--

DROP TABLE IF EXISTS `liveupdates`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `liveupdates` (
  `updateID` int(11) NOT NULL DEFAULT '0',
  `updateName` varchar(100) DEFAULT NULL,
  `description` varchar(100) DEFAULT NULL,
  `machoVersionMin` int(11) DEFAULT NULL,
  `machoVersionMax` int(11) DEFAULT NULL,
  `buildNumberMin` int(11) DEFAULT NULL,
  `buildNumberMax` int(11) DEFAULT NULL,
  `methodName` varchar(100) DEFAULT NULL,
  `objectID` varchar(100) DEFAULT NULL,
  `codeType` varchar(100) DEFAULT NULL,
  `code` blob,
  PRIMARY KEY (`updateID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `liveupdates`
--

LOCK TABLES `liveupdates` WRITE;
/*!40000 ALTER TABLE `liveupdates` DISABLE KEYS */;
INSERT INTO `liveupdates` VALUES (1,'PhotoUpload','Generated by liveupdategen',1,330,1,500000,'AskForPortraitConfirmation','uicls.CharacterCreationLayer::CharacterCreationLayer','globalClassMethod','c\0\0\0\0\0\0\0\0\0G\0\0\0s∫\0\0\0|\0\0j\0\0É\0\0}\0|\0\0j\0|\0\0j\0É\0}\0t\0|\0d\0É\0}\0|\0j\0É\0\0}\0|\0j\0É\0\0t\0j\0d\0i\0d\0d\06É\0t\0j \0d\0É\0}\0|\0d\0\0k\0sÅ\0|\0t\0k\0rõ\0t\0j\0d\0i\0d\0d\06É\0n\0t\0j\0d\0i\0d\0d\06É\0t\0Sd\0\0S(\0\0\0Nt\0\0\0rbt\0\0\0CustomNotifys*\0\0\0Uploading your character portrait to EVEMut\0\0\0notifyt\0\0\0photoUploadSvcs\0\0\0Portrait upload failed!s\0\0\0Portrait upload successful!(\r\0\0\0t\0\0\0GetActivePortraitt\0\0\0GetPortraitSnapshotPatht\0\0\0activePortraitIndext\0\0\0opent\0\0\0readt\0\0\0closet\0\0\0evet\0\0\0Messaget\0\0\0smt \0\0\0RemoteSvct\0\0\0Nonet\0\0\0Falset\0\0\0True(\0\0\0t\0\0\0selft\0\0\0argst\0\0\0photot\0\0\0snapPatht  \0\0\0photoFilet    \0\0\0photoDatat\0\0\0result(\0\0\0\0(\0\0\0\0s\0\0\0<string>t\Z\0\0\0AskForPortraitConfirmation\0\0\0s\0\0\0\0\n\Z');
/*!40000 ALTER TABLE `liveupdates` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2011-12-16 11:10:11
